services:
  postgres:
    image: postgres:16-alpine
    container_name: assignment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5434:5432"
    volumes:
      - assignment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - assignment-network

  ingestion:
    build: ./packages/ingestor
    container_name: assignment-ingestion
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - assignment-network

volumes:
  assignment_postgres_data:

networks:
  assignment-network:
    driver: bridge